# Generated by Django 5.2 on 2025-06-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "address_ID",
                    models.AutoField(
                        db_column="address_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "address_street",
                    models.CharField(
                        blank=True,
                        db_column="address_street",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "address_city",
                    models.CharField(
                        blank=True, db_column="address_city", max_length=100, null=True
                    ),
                ),
                (
                    "address_state",
                    models.CharField(
                        blank=True, db_column="address_state", max_length=100, null=True
                    ),
                ),
                (
                    "address_zip_code",
                    models.CharField(
                        blank=True,
                        db_column="address_zip_code",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address_country",
                    models.CharField(
                        blank=True,
                        db_column="address_country",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "Address",
            },
        ),
        migrations.CreateModel(
            name="Departament",
            fields=[
                (
                    "department_ID",
                    models.AutoField(
                        db_column="department_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "department_name",
                    models.CharField(db_column="department_name", max_length=100),
                ),
                (
                    "department_description",
                    models.TextField(
                        blank=True, db_column="department_description", null=True
                    ),
                ),
                (
                    "department_phone",
                    models.CharField(
                        blank=True,
                        db_column="department_phone",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "department_created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="department_created_at"
                    ),
                ),
                (
                    "department_manager",
                    models.CharField(
                        blank=True,
                        db_column="department_manager",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "department_address",
                    models.ForeignKey(
                        blank=True,
                        db_column="department_address",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departament.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "Departament",
                "ordering": ["department_name"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_ID",
                    models.AutoField(
                        db_column="employee_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(db_column="employee_name", max_length=100),
                ),
                (
                    "employee_email",
                    models.EmailField(
                        blank=True,
                        db_column="employee_email",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "employee_phone",
                    models.CharField(
                        blank=True, db_column="employee_phone", max_length=15, null=True
                    ),
                ),
                (
                    "employee_birth_date",
                    models.DateField(
                        blank=True, db_column="employee_birth_date", null=True
                    ),
                ),
                (
                    "employee_hire_date",
                    models.DateTimeField(
                        auto_now_add=True, db_column="employee_hire_date"
                    ),
                ),
                (
                    "employee_address",
                    models.ForeignKey(
                        blank=True,
                        db_column="employee_address",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departament.address",
                    ),
                ),
                (
                    "employee_department",
                    models.ForeignKey(
                        db_column="employee_department",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departament.departament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "db_table": "Employee",
                "ordering": ["employee_name"],
            },
        ),
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "function_ID",
                    models.AutoField(
                        db_column="function_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "function_title",
                    models.CharField(db_column="function_title", max_length=100),
                ),
                (
                    "function_salary",
                    models.DecimalField(
                        blank=True,
                        db_column="function_salary",
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "function_manager",
                    models.CharField(
                        blank=True,
                        db_column="function_manager",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "function_employee",
                    models.ForeignKey(
                        blank=True,
                        db_column="function_employee",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departament.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Função",
                "verbose_name_plural": "Funções",
                "db_table": "Function",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_function",
            field=models.ForeignKey(
                blank=True,
                db_column="employee_function",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="departament.function",
            ),
        ),
    ]
